### PR TITLE
DI-1

### LINKED ISSUE #333: JabRef Groups interface should work at low resolutions 1366x768
1366x768 - top and bottom bar is there, "OK" button cannot be pressed

### PR DESCRIPTION
**Pull request by calixtus**
### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
This is an alternative to use [Google's Dagger](https://dagger.dev/) , which was tried out 2.5 years ago at https://github.com/koppor/jabref/pull/518

**Comment by koppor** [comment]
We can use this PR to do a proper renaming:

Please swap the names "PreferenceService" and "Preferences".

Reason:

- A `Service` is a singleton providing things (see https://javaee.github.io/hk2/apidocs/org/jvnet/hk2/annotations/Service.html)
- A `Contract` is a thing what a service is providing (see https://javaee.github.io/hk2/apidocs/org/jvnet/hk2/annotations/Contract.html)
- In our case the (current) `PreferencesService` is the contract fulfilled by `Preferences`. -- And it should be the other way round.

**Comment by koppor** [comment]
I think, this is the right place to provide the link to some naming hints and usages https://github.com/JabRef/jabref/pull/6103#issuecomment-1742103784

**Comment by calixtus** [comment]
> We can use this PR to do a proper renaming:
> 
> Please swap the names "PreferenceService" and "Preferences".

Can we postpone this to a follow up PR. I believe this one is on the edge of what can be understood in one PR.
Thats why I called the PR DI-_1_ 😄 
I just wanted to finally get rid of Globals and prepare the next steps by unifying the access and the injection method.

**Comment by koppor** [comment]
Follow-up at https://github.com/JabRef/jabref/pull/11342

**Comment by koppor** [comment]
> > We can use this PR to do a proper renaming:
> > Please swap the names "PreferenceService" and "Preferences".
> 
> Can we postpone this to a follow up PR?

Please directly after merge as DI-2.

**Pull request closed without merging**
